<a href="https://colab.research.google.com/github/Anand-s-cmd/ML_Use_cases/blob/main/debugging_hospital.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)  # or 1000
pd.set_option('display.max_rows', None)  # or 1000
pd.set_option('display.max_colwidth', None)  # or 199
import pandas as pd
import pandas as pd
#Univariate Analysis
#data visualisation
import seaborn as sns     
sns.set()
import matplotlib.pyplot as plt
%matplotlib inline
import datetime as dt
import warnings; warnings.simplefilter('ignore')
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import KFold, StratifiedKFold, train_test_split
from sklearn.metrics import roc_auc_score, accuracy_score, confusion_matrix, roc_curve, precision_score, recall_score, precision_recall_curve
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
warnings.simplefilter(action='ignore', category=UserWarning)

In [7]:
df=pd.read_csv('/content/drive/MyDrive/Hospital/Dataset.csv')

In [8]:
df.shape

(91713, 186)

In [9]:
df3=df

In [10]:
#Lets drop Id's
df3.drop('encounter_id',inplace=True,axis=1)
df3.drop('patient_id',inplace=True,axis=1)
df3.drop('hospital_id',inplace=True,axis=1)

In [11]:
df3.shape

(91713, 183)

##BELOW I HAVE TRIED TWO APPROACHES LIKE ONE IS THROUGH METHD ONE IS THROUGH NORMAL LINES OF CODE 
##BECAUSE 
##JUST WANTED TO KNOW IN THE FUNCTION LAST WHAT IS THE TYPE OF THE VALUE 

df_missing

#APPROACH 1)

In [ ]:
#Missing value analysis 
# List of normalized Missing values 
#Step 1 Count missing values 
def missing_values_table(df):
        #Extract columns names first
        columns=df3.columns

        # Total missing values
        mis_val = df.isnull().sum()
        
        # Percentage of missing values
        mis_val_percent = 100 * df.isnull().sum() / len(df)
        
        #Take the data types
        data_type = df.dtypes

        #Check all the values are having which DATA TYPES
        print(type(columns))
        print(type(mis_val))
        print(type(mis_val_percent))
        print(type(data_type))

        #(columns) is <class 'pandas.core.indexes.base.Index'> so we should convert it to Series using [idx.to_series()] method
        columns=columns.to_series()

        print("After converting columns to series",type(columns))

        
        # Make a table with the results
        mis_val_table = pd.concat([columns, mis_val, mis_val_percent,data_type], axis=1)
        
        # Rename the columns
        mis_val_table_ren_columns = mis_val_table.rename(columns = {0 : 'columns', 1 : 'Missing Values', 2 : '% of Total Values',3:'Data_Types'})
        
        # Sort the table by percentage of missing descending
        mis_val_table_ren_columns = mis_val_table_ren_columns[
            mis_val_table_ren_columns.iloc[:,1] != 0].sort_values(
        '% of Total Values', ascending=False).round(1)
        
        # Print some summary information
        print ("Your selected dataframe has " + str(df.shape[1]) + " columns.\n"      
            "There are " + str(mis_val_table_ren_columns.shape[0]) +
              " columns that have missing values.")
        
        # Return the dataframe with missing information
        return mis_val_table_ren_columns

In [ ]:
missing_values_table(df3)

<class 'pandas.core.indexes.base.Index'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
After converting columns to series <class 'pandas.core.series.Series'>
Your selected dataframe has 183 columns.
There are 175 columns that have missing values.

,columns,Missing Values,% of Total Values,Data_Types
h1_bilirubin_max,h1_bilirubin_max,84619,92.3,float64
h1_bilirubin_min,h1_bilirubin_min,84619,92.3,float64
h1_lactate_min,h1_lactate_min,84369,92.0,float64
h1_lactate_max,h1_lactate_max,84369,92.0,float64
h1_albumin_max,h1_albumin_max,83824,91.4,float64
h1_albumin_min,h1_albumin_min,83824,91.4,float64
h1_pao2fio2ratio_min,h1_pao2fio2ratio_min,80195,87.4,float64
h1_pao2fio2ratio_max,h1_pao2fio2ratio_max,80195,87.4,float64
h1_arterial_ph_min,h1_arterial_ph_min,76424,83.3,float64
h1_arterial_ph_max,h1_arterial_ph_max,76424,83.3,float64
h1_hco3_min,h1_hco3_min,76094,83.0,float64
h1_hco3_max,h1_hco3_max,76094,83.0,float64
h1_arterial_pco2_min,h1_arterial_pco2_min,75959,82.8,float64
h1_arterial_pco2_max,h1_arterial_pco2_max,75959,82.8,float64
h1_wbc_max,h1_wbc_max,75953,82.8,float64
h1_wbc_min,h1_wbc_min,75953,82.8,float64
h1_arterial_po2_max,h1_arterial_po2_max,75945,82.8,float64
h1_arterial_po2_min,h1_arterial_po2_min,75945,82.8,float64
h1_calcium_min,h1_calcium_min,75863,82.7,float64
h1_calcium_max,h1_calcium_max,75863,82.7,float64
h1_platelets_max,h1_platelets_max,75673,82.5,float64
h1_platelets_min,h1_platelets_min,75673,82.5,float64
h1_bun_min,h1_bun_min,75091,81.9,float64
h1_bun_max,h1_bun_max,75091,81.9,float64
h1_creatinine_min,h1_creatinine_min,74957,81.7,float64
h1_creatinine_max,h1_creatinine_max,74957,81.7,float64
h1_diasbp_invasive_max,h1_diasbp_invasive_max,74928,81.7,float64
h1_diasbp_invasive_min,h1_diasbp_invasive_min,74928,81.7,float64
h1_sysbp_invasive_max,h1_sysbp_invasive_max,74915,81.7,float64
h1_sysbp_invasive_min,h1_sysbp_invasive_min,74915,81.7,float64
h1_mbp_invasive_min,h1_mbp_invasive_min,74844,81.6,float64
h1_mbp_invasive_max,h1_mbp_invasive_max,74844,81.6,float64
h1_hematocrit_min,h1_hematocrit_min,73420,80.1,float64
h1_hematocrit_max,h1_hematocrit_max,73420,80.1,float64
h1_hemaglobin_max,h1_hemaglobin_max,73123,79.7,float64
h1_hemaglobin_min,h1_hemaglobin_min,73123,79.7,float64
h1_sodium_max,h1_sodium_max,72617,79.2,float64
h1_sodium_min,h1_sodium_min,72617,79.2,float64
h1_potassium_min,h1_potassium_min,72102,78.6,float64
h1_potassium_max,h1_potassium_max,72102,78.6,float64
ph_apache,ph_apache,70868,77.3,float64
pao2_apache,pao2_apache,70868,77.3,float64
paco2_for_ph_apache,paco2_for_ph_apache,70868,77.3,float64
paco2_apache,paco2_apache,70868,77.3,float64
fio2_apache,fio2_apache,70868,77.3,float64
d1_lactate_max,d1_lactate_max,68396,74.6,float64
d1_lactate_min,d1_lactate_min,68396,74.6,float64
d1_diasbp_invasive_min,d1_diasbp_invasive_min,67984,74.1,float64
d1_diasbp_invasive_max,d1_diasbp_invasive_max,67984,74.1,float64
d1_sysbp_invasive_max,d1_sysbp_invasive_max,67959,74.1,float64
d1_sysbp_invasive_min,d1_sysbp_invasive_min,67959,74.1,float64
d1_mbp_invasive_min,d1_mbp_invasive_min,67777,73.9,float64
d1_mbp_invasive_max,d1_mbp_invasive_max,67777,73.9,float64
d1_pao2fio2ratio_min,d1_pao2fio2ratio_min,66008,72.0,float64
d1_pao2fio2ratio_max,d1_pao2fio2ratio_max,66008,72.0,float64
d1_arterial_ph_min,d1_arterial_ph_min,60123,65.6,float64
d1_arterial_ph_max,d1_arterial_ph_max,60123,65.6,float64
d1_arterial_pco2_max,d1_arterial_pco2_max,59271,64.6,float64
d1_arterial_pco2_min,d1_arterial_pco2_min,59271,64.6,float64
d1_arterial_po2_min,d1_arterial_po2_min,59262,64.6,float64
d1_arterial_po2_max,d1_arterial_po2_max,59262,64.6,float64
bilirubin_apache,bilirubin_apache,58134,63.4,float64
h1_inr_max,h1_inr_max,57941,63.2,float64
d1_inr_min,d1_inr_min,57941,63.2,float64
h1_inr_min,h1_inr_min,57941,63.2,float64
d1_inr_max,d1_inr_max,57941,63.2,float64
albumin_apache,albumin_apache,54379,59.3,float64
d1_bilirubin_min,d1_bilirubin_min,53673,58.5,float64
d1_bilirubin_max,d1_bilirubin_max,53673,58.5,float64
h1_glucose_min,h1_glucose_min,52614,57.4,float64
h1_glucose_max,h1_glucose_max,52614,57.4,float64
d1_albumin_min,d1_albumin_min,49096,53.5,float64
d1_albumin_max,d1_albumin_max,49096,53.5,float64
urineoutput_apache,urineoutput_apache,48998,53.4,float64
wbc_apache,wbc_apache,22012,24.0,float64
h1_temp_min,h1_temp_min,21732,23.7,float64
h1_temp_max,h1_temp_max,21732,23.7,float64
hospital_admit_source,hospital_admit_source,21409,23.3,object
hematocrit_apache,hematocrit_apache,19878,21.7,float64
bun_apache,bun_apache,19262,21.0,float64
creatinine_apache,creatinine_apache,18853,20.6,float64
sodium_apache,sodium_apache,18600,20.3,float64
d1_hco3_max,d1_hco3_max,15071,16.4,float64
d1_hco3_min,d1_hco3_min,15071,16.4,float64
d1_platelets_max,d1_platelets_max,13444,14.7,float64
d1_platelets_min,d1_platelets_min,13444,14.7,float64
d1_wbc_max,d1_wbc_max,13174,14.4,float64
d1_wbc_min,d1_wbc_min,13174,14.4,float64
d1_calcium_max,d1_calcium_max,13069,14.2,float64
d1_calcium_min,d1_calcium_min,13069,14.2,float64
d1_hemaglobin_min,d1_hemaglobin_min,12147,13.2,float64
d1_hemaglobin_max,d1_hemaglobin_max,12147,13.2,float64
d1_hematocrit_min,d1_hematocrit_min,11654,12.7,float64
d1_hematocrit_max,d1_hematocrit_max,11654,12.7,float64
glucose_apache,glucose_apache,11036,12.0,float64
d1_bun_max,d1_bun_max,10514,11.5,float64
d1_bun_min,d1_bun_min,10514,11.5,float64
d1_sodium_max,d1_sodium_max,10195,11.1,float64
d1_sodium_min,d1_sodium_min,10195,11.1,float64
d1_creatinine_max,d1_creatinine_max,10169,11.1,float64
d1_creatinine_min,d1_creatinine_min,10169,11.1,float64
d1_potassium_min,d1_potassium_min,9585,10.5,float64
d1_potassium_max,d1_potassium_max,9585,10.5,float64
h1_mbp_noninvasive_max,h1_mbp_noninvasive_max,9084,9.9,float64
h1_mbp_noninvasive_min,h1_mbp_noninvasive_min,9084,9.9,float64
apache_4a_hospital_death_prob,apache_4a_hospital_death_prob,7947,8.7,float64
apache_4a_icu_death_prob,apache_4a_icu_death_prob,7947,8.7,float64
h1_diasbp_noninvasive_max,h1_diasbp_noninvasive_max,7350,8.0,float64
h1_diasbp_noninvasive_min,h1_diasbp_noninvasive_min,7350,8.0,float64
h1_sysbp_noninvasive_max,h1_sysbp_noninvasive_max,7341,8.0,float64
h1_sysbp_noninvasive_min,h1_sysbp_noninvasive_min,7341,8.0,float64
d1_glucose_max,d1_glucose_max,5807,6.3,float64
d1_glucose_min,d1_glucose_min,5807,6.3,float64
h1_mbp_max,h1_mbp_max,4639,5.1,float64
h1_mbp_min,h1_mbp_min,4639,5.1,float64
h1_resprate_min,h1_resprate_min,4357,4.8,float64
h1_resprate_max,h1_resprate_max,4357,4.8,float64
age,age,4228,4.6,float64
h1_spo2_min,h1_spo2_min,4185,4.6,float64
h1_spo2_max,h1_spo2_max,4185,4.6,float64
temp_apache,temp_apache,4108,4.5,float64
h1_diasbp_min,h1_diasbp_min,3619,3.9,float64
h1_diasbp_max,h1_diasbp_max,3619,3.9,float64
h1_sysbp_max,h1_sysbp_max,3611,3.9,float64
h1_sysbp_min,h1_sysbp_min,3611,3.9,float64
bmi,bmi,3429,3.7,float64
h1_heartrate_max,h1_heartrate_max,2790,3.0,float64
h1_heartrate_min,h1_heartrate_min,2790,3.0,float64
weight,weight,2720,3.0,float64
d1_temp_max,d1_temp_max,2324,2.5,float64
d1_temp_min,d1_temp_min,2324,2.5,float64
gcs_eyes_apache,gcs_eyes_apache,1901,2.1,float64
gcs_motor_apache,gcs_motor_apache,1901,2.1,float64
gcs_verbal_apache,gcs_verbal_apache,1901,2.1,float64
apache_3j_bodysystem,apache_3j_bodysystem,1662,1.8,object
apache_2_diagnosis,apache_2_diagnosis,1662,1.8,float64
apache_2_bodysystem,apache_2_bodysystem,1662,1.8,object
d1_mbp_noninvasive_min,d1_mbp_noninvasive_min,1479,1.6,float64
d1_mbp_noninvasive_max,d1_mbp_noninvasive_max,1479,1.6,float64
ethnicity,ethnicity,1395,1.5,object
height,height,1334,1.5,float64
resprate_apache,resprate_apache,1234,1.3,float64
apache_3j_diagnosis,apache_3j_diagnosis,1101,1.2,float64
d1_diasbp_noninvasive_min,d1_diasbp_noninvasive_min,1040,1.1,float64
d1_diasbp_noninvasive_max,d1_diasbp_noninvasive_max,1040,1.1,float64
gcs_unable_apache,gcs_unable_apache,1037,1.1,float64
d1_sysbp_noninvasive_min,d1_sysbp_noninvasive_min,1027,1.1,float64
d1_sysbp_noninvasive_max,d1_sysbp_noninvasive_max,1027,1.1,float64
map_apache,map_apache,994,1.1,float64
heart_rate_apache,heart_rate_apache,878,1.0,float64
lymphoma,lymphoma,715,0.8,float64
intubated_apache,intubated_apache,715,0.8,float64
aids,aids,715,0.8,float64
hepatic_failure,hepatic_failure,715,0.8,float64
immunosuppression,immunosuppression,715,0.8,float64
solid_tumor_with_metastasis,solid_tumor_with_metastasis,715,0.8,float64
leukemia,leukemia,715,0.8,float64
cirrhosis,cirrhosis,715,0.8,float64
arf_apache,arf_apache,715,0.8,float64
ventilated_apache,ventilated_apache,715,0.8,float64
diabetes_mellitus,diabetes_mellitus,715,0.8,float64
d1_resprate_max,d1_resprate_max,385,0.4,float64
d1_resprate_min,d1_resprate_min,385,0.4,float64
d1_spo2_min,d1_spo2_min,333,0.4,float64
d1_spo2_max,d1_spo2_max,333,0.4,float64
d1_mbp_max,d1_mbp_max,220,0.2,float64
d1_mbp_min,d1_mbp_min,220,0.2,float64
d1_diasbp_max,d1_diasbp_max,165,0.2,float64
d1_diasbp_min,d1_diasbp_min,165,0.2,float64
d1_sysbp_min,d1_sysbp_min,159,0.2,float64
d1_sysbp_max,d1_sysbp_max,159,0.2,float64
d1_heartrate_max,d1_heartrate_max,145,0.2,float64
d1_heartrate_min,d1_heartrate_min,145,0.2,float64
icu_admit_source,icu_admit_source,112,0.1,object
gender,gender,25,0.0,object

In [ ]:
df_missing= missing_values_table(df3)

<class 'pandas.core.indexes.base.Index'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
After converting columns to series <class 'pandas.core.series.Series'>
Your selected dataframe has 183 columns.
There are 175 columns that have missing values.

In [ ]:
df_missing

,columns,Missing Values,% of Total Values,Data_Types
h1_bilirubin_max,h1_bilirubin_max,84619,92.3,float64
h1_bilirubin_min,h1_bilirubin_min,84619,92.3,float64
h1_lactate_min,h1_lactate_min,84369,92.0,float64
h1_lactate_max,h1_lactate_max,84369,92.0,float64
h1_albumin_max,h1_albumin_max,83824,91.4,float64
h1_albumin_min,h1_albumin_min,83824,91.4,float64
h1_pao2fio2ratio_min,h1_pao2fio2ratio_min,80195,87.4,float64
h1_pao2fio2ratio_max,h1_pao2fio2ratio_max,80195,87.4,float64
h1_arterial_ph_min,h1_arterial_ph_min,76424,83.3,float64
h1_arterial_ph_max,h1_arterial_ph_max,76424,83.3,float64
h1_hco3_min,h1_hco3_min,76094,83.0,float64
h1_hco3_max,h1_hco3_max,76094,83.0,float64
h1_arterial_pco2_min,h1_arterial_pco2_min,75959,82.8,float64
h1_arterial_pco2_max,h1_arterial_pco2_max,75959,82.8,float64
h1_wbc_max,h1_wbc_max,75953,82.8,float64
h1_wbc_min,h1_wbc_min,75953,82.8,float64
h1_arterial_po2_max,h1_arterial_po2_max,75945,82.8,float64
h1_arterial_po2_min,h1_arterial_po2_min,75945,82.8,float64
h1_calcium_min,h1_calcium_min,75863,82.7,float64
h1_calcium_max,h1_calcium_max,75863,82.7,float64
h1_platelets_max,h1_platelets_max,75673,82.5,float64
h1_platelets_min,h1_platelets_min,75673,82.5,float64
h1_bun_min,h1_bun_min,75091,81.9,float64
h1_bun_max,h1_bun_max,75091,81.9,float64
h1_creatinine_min,h1_creatinine_min,74957,81.7,float64
h1_creatinine_max,h1_creatinine_max,74957,81.7,float64
h1_diasbp_invasive_max,h1_diasbp_invasive_max,74928,81.7,float64
h1_diasbp_invasive_min,h1_diasbp_invasive_min,74928,81.7,float64
h1_sysbp_invasive_max,h1_sysbp_invasive_max,74915,81.7,float64
h1_sysbp_invasive_min,h1_sysbp_invasive_min,74915,81.7,float64
h1_mbp_invasive_min,h1_mbp_invasive_min,74844,81.6,float64
h1_mbp_invasive_max,h1_mbp_invasive_max,74844,81.6,float64
h1_hematocrit_min,h1_hematocrit_min,73420,80.1,float64
h1_hematocrit_max,h1_hematocrit_max,73420,80.1,float64
h1_hemaglobin_max,h1_hemaglobin_max,73123,79.7,float64
h1_hemaglobin_min,h1_hemaglobin_min,73123,79.7,float64
h1_sodium_max,h1_sodium_max,72617,79.2,float64
h1_sodium_min,h1_sodium_min,72617,79.2,float64
h1_potassium_min,h1_potassium_min,72102,78.6,float64
h1_potassium_max,h1_potassium_max,72102,78.6,float64
ph_apache,ph_apache,70868,77.3,float64
pao2_apache,pao2_apache,70868,77.3,float64
paco2_for_ph_apache,paco2_for_ph_apache,70868,77.3,float64
paco2_apache,paco2_apache,70868,77.3,float64
fio2_apache,fio2_apache,70868,77.3,float64
d1_lactate_max,d1_lactate_max,68396,74.6,float64
d1_lactate_min,d1_lactate_min,68396,74.6,float64
d1_diasbp_invasive_min,d1_diasbp_invasive_min,67984,74.1,float64
d1_diasbp_invasive_max,d1_diasbp_invasive_max,67984,74.1,float64
d1_sysbp_invasive_max,d1_sysbp_invasive_max,67959,74.1,float64
d1_sysbp_invasive_min,d1_sysbp_invasive_min,67959,74.1,float64
d1_mbp_invasive_min,d1_mbp_invasive_min,67777,73.9,float64
d1_mbp_invasive_max,d1_mbp_invasive_max,67777,73.9,float64
d1_pao2fio2ratio_min,d1_pao2fio2ratio_min,66008,72.0,float64
d1_pao2fio2ratio_max,d1_pao2fio2ratio_max,66008,72.0,float64
d1_arterial_ph_min,d1_arterial_ph_min,60123,65.6,float64
d1_arterial_ph_max,d1_arterial_ph_max,60123,65.6,float64
d1_arterial_pco2_max,d1_arterial_pco2_max,59271,64.6,float64
d1_arterial_pco2_min,d1_arterial_pco2_min,59271,64.6,float64
d1_arterial_po2_min,d1_arterial_po2_min,59262,64.6,float64
d1_arterial_po2_max,d1_arterial_po2_max,59262,64.6,float64
bilirubin_apache,bilirubin_apache,58134,63.4,float64
h1_inr_max,h1_inr_max,57941,63.2,float64
d1_inr_min,d1_inr_min,57941,63.2,float64
h1_inr_min,h1_inr_min,57941,63.2,float64
d1_inr_max,d1_inr_max,57941,63.2,float64
albumin_apache,albumin_apache,54379,59.3,float64
d1_bilirubin_min,d1_bilirubin_min,53673,58.5,float64
d1_bilirubin_max,d1_bilirubin_max,53673,58.5,float64
h1_glucose_min,h1_glucose_min,52614,57.4,float64
h1_glucose_max,h1_glucose_max,52614,57.4,float64
d1_albumin_min,d1_albumin_min,49096,53.5,float64
d1_albumin_max,d1_albumin_max,49096,53.5,float64
urineoutput_apache,urineoutput_apache,48998,53.4,float64
wbc_apache,wbc_apache,22012,24.0,float64
h1_temp_min,h1_temp_min,21732,23.7,float64
h1_temp_max,h1_temp_max,21732,23.7,float64
hospital_admit_source,hospital_admit_source,21409,23.3,object
hematocrit_apache,hematocrit_apache,19878,21.7,float64
bun_apache,bun_apache,19262,21.0,float64
creatinine_apache,creatinine_apache,18853,20.6,float64
sodium_apache,sodium_apache,18600,20.3,float64
d1_hco3_max,d1_hco3_max,15071,16.4,float64
d1_hco3_min,d1_hco3_min,15071,16.4,float64
d1_platelets_max,d1_platelets_max,13444,14.7,float64
d1_platelets_min,d1_platelets_min,13444,14.7,float64
d1_wbc_max,d1_wbc_max,13174,14.4,float64
d1_wbc_min,d1_wbc_min,13174,14.4,float64
d1_calcium_max,d1_calcium_max,13069,14.2,float64
d1_calcium_min,d1_calcium_min,13069,14.2,float64
d1_hemaglobin_min,d1_hemaglobin_min,12147,13.2,float64
d1_hemaglobin_max,d1_hemaglobin_max,12147,13.2,float64
d1_hematocrit_min,d1_hematocrit_min,11654,12.7,float64
d1_hematocrit_max,d1_hematocrit_max,11654,12.7,float64
glucose_apache,glucose_apache,11036,12.0,float64
d1_bun_max,d1_bun_max,10514,11.5,float64
d1_bun_min,d1_bun_min,10514,11.5,float64
d1_sodium_max,d1_sodium_max,10195,11.1,float64
d1_sodium_min,d1_sodium_min,10195,11.1,float64
d1_creatinine_max,d1_creatinine_max,10169,11.1,float64
d1_creatinine_min,d1_creatinine_min,10169,11.1,float64
d1_potassium_min,d1_potassium_min,9585,10.5,float64
d1_potassium_max,d1_potassium_max,9585,10.5,float64
h1_mbp_noninvasive_max,h1_mbp_noninvasive_max,9084,9.9,float64
h1_mbp_noninvasive_min,h1_mbp_noninvasive_min,9084,9.9,float64
apache_4a_hospital_death_prob,apache_4a_hospital_death_prob,7947,8.7,float64
apache_4a_icu_death_prob,apache_4a_icu_death_prob,7947,8.7,float64
h1_diasbp_noninvasive_max,h1_diasbp_noninvasive_max,7350,8.0,float64
h1_diasbp_noninvasive_min,h1_diasbp_noninvasive_min,7350,8.0,float64
h1_sysbp_noninvasive_max,h1_sysbp_noninvasive_max,7341,8.0,float64
h1_sysbp_noninvasive_min,h1_sysbp_noninvasive_min,7341,8.0,float64
d1_glucose_max,d1_glucose_max,5807,6.3,float64
d1_glucose_min,d1_glucose_min,5807,6.3,float64
h1_mbp_max,h1_mbp_max,4639,5.1,float64
h1_mbp_min,h1_mbp_min,4639,5.1,float64
h1_resprate_min,h1_resprate_min,4357,4.8,float64
h1_resprate_max,h1_resprate_max,4357,4.8,float64
age,age,4228,4.6,float64
h1_spo2_min,h1_spo2_min,4185,4.6,float64
h1_spo2_max,h1_spo2_max,4185,4.6,float64
temp_apache,temp_apache,4108,4.5,float64
h1_diasbp_min,h1_diasbp_min,3619,3.9,float64
h1_diasbp_max,h1_diasbp_max,3619,3.9,float64
h1_sysbp_max,h1_sysbp_max,3611,3.9,float64
h1_sysbp_min,h1_sysbp_min,3611,3.9,float64
bmi,bmi,3429,3.7,float64
h1_heartrate_max,h1_heartrate_max,2790,3.0,float64
h1_heartrate_min,h1_heartrate_min,2790,3.0,float64
weight,weight,2720,3.0,float64
d1_temp_max,d1_temp_max,2324,2.5,float64
d1_temp_min,d1_temp_min,2324,2.5,float64
gcs_eyes_apache,gcs_eyes_apache,1901,2.1,float64
gcs_motor_apache,gcs_motor_apache,1901,2.1,float64
gcs_verbal_apache,gcs_verbal_apache,1901,2.1,float64
apache_3j_bodysystem,apache_3j_bodysystem,1662,1.8,object
apache_2_diagnosis,apache_2_diagnosis,1662,1.8,float64
apache_2_bodysystem,apache_2_bodysystem,1662,1.8,object
d1_mbp_noninvasive_min,d1_mbp_noninvasive_min,1479,1.6,float64
d1_mbp_noninvasive_max,d1_mbp_noninvasive_max,1479,1.6,float64
ethnicity,ethnicity,1395,1.5,object
height,height,1334,1.5,float64
resprate_apache,resprate_apache,1234,1.3,float64
apache_3j_diagnosis,apache_3j_diagnosis,1101,1.2,float64
d1_diasbp_noninvasive_min,d1_diasbp_noninvasive_min,1040,1.1,float64
d1_diasbp_noninvasive_max,d1_diasbp_noninvasive_max,1040,1.1,float64
gcs_unable_apache,gcs_unable_apache,1037,1.1,float64
d1_sysbp_noninvasive_min,d1_sysbp_noninvasive_min,1027,1.1,float64
d1_sysbp_noninvasive_max,d1_sysbp_noninvasive_max,1027,1.1,float64
map_apache,map_apache,994,1.1,float64
heart_rate_apache,heart_rate_apache,878,1.0,float64
lymphoma,lymphoma,715,0.8,float64
intubated_apache,intubated_apache,715,0.8,float64
aids,aids,715,0.8,float64
hepatic_failure,hepatic_failure,715,0.8,float64
immunosuppression,immunosuppression,715,0.8,float64
solid_tumor_with_metastasis,solid_tumor_with_metastasis,715,0.8,float64
leukemia,leukemia,715,0.8,float64
cirrhosis,cirrhosis,715,0.8,float64
arf_apache,arf_apache,715,0.8,float64
ventilated_apache,ventilated_apache,715,0.8,float64
diabetes_mellitus,diabetes_mellitus,715,0.8,float64
d1_resprate_max,d1_resprate_max,385,0.4,float64
d1_resprate_min,d1_resprate_min,385,0.4,float64
d1_spo2_min,d1_spo2_min,333,0.4,float64
d1_spo2_max,d1_spo2_max,333,0.4,float64
d1_mbp_max,d1_mbp_max,220,0.2,float64
d1_mbp_min,d1_mbp_min,220,0.2,float64
d1_diasbp_max,d1_diasbp_max,165,0.2,float64
d1_diasbp_min,d1_diasbp_min,165,0.2,float64
d1_sysbp_min,d1_sysbp_min,159,0.2,float64
d1_sysbp_max,d1_sysbp_max,159,0.2,float64
d1_heartrate_max,d1_heartrate_max,145,0.2,float64
d1_heartrate_min,d1_heartrate_min,145,0.2,float64
icu_admit_source,icu_admit_source,112,0.1,object
gender,gender,25,0.0,object

In [ ]:
type(df_missing)

pandas.core.frame.DataFrame

#APPROACH 2)

In [ ]:
mis_val = df3.isnull().sum()
mis_val_percent = 100 * df.isnull().sum() / len(df3)
data_type = df3.dtypes
columns=df3.columns

#mis_val_table = pd.concat([columns, mis_val, mis_val_percent,data_type], axis=1)

In [ ]:
print(type(columns))
print(type(mis_val))
print(type(mis_val_percent))
print(type(data_type))

<class 'pandas.core.indexes.base.Index'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>

###(columns) is <class 'pandas.core.indexes.base.Index'> so we should convert it to Series using [idx.to_series()] method

In [ ]:
columns=columns.to_series()

In [ ]:
print(type(columns))

<class 'pandas.core.series.Series'>

In [ ]:
mis_val_table = pd.concat([columns, mis_val, mis_val_percent,data_type], axis=1)

In [ ]:
mis_val_table_ren_columns = mis_val_table.rename(columns = {0 : 'columns', 1 : 'Missing Values', 2 : '% of Total Values',3:'Data_Types'})

In [ ]:
 mis_val_table_ren_columns[mis_val_table_ren_columns.iloc[:,1] != 0]
            #train_df_mv_norm.iloc[:,1:] will select all rows but your first column will be excluded.
            #MEANS HERE IN THEFIRST COLOMN LIKE age, bmi, ethnicity THAT VALUE SHOULD NOT BE ZERO THATS WHY THEY ARE USING 
            # iloc[:,1] != 0]

,columns,Missing Values,% of Total Values,Data_Types
age,age,4228,4.610033,float64
bmi,bmi,3429,3.738837,float64
ethnicity,ethnicity,1395,1.521049,object
gender,gender,25,0.027259,object
height,height,1334,1.454538,float64
hospital_admit_source,hospital_admit_source,21409,23.343474,object
icu_admit_source,icu_admit_source,112,0.122120,object
weight,weight,2720,2.965774,float64
albumin_apache,albumin_apache,54379,59.292576,float64
apache_2_diagnosis,apache_2_diagnosis,1662,1.812175,float64
apache_3j_diagnosis,apache_3j_diagnosis,1101,1.200484,float64
arf_apache,arf_apache,715,0.779606,float64
bilirubin_apache,bilirubin_apache,58134,63.386870,float64
bun_apache,bun_apache,19262,21.002475,float64
creatinine_apache,creatinine_apache,18853,20.556519,float64
fio2_apache,fio2_apache,70868,77.271488,float64
gcs_eyes_apache,gcs_eyes_apache,1901,2.072770,float64
gcs_motor_apache,gcs_motor_apache,1901,2.072770,float64
gcs_unable_apache,gcs_unable_apache,1037,1.130701,float64
gcs_verbal_apache,gcs_verbal_apache,1901,2.072770,float64
glucose_apache,glucose_apache,11036,12.033190,float64
heart_rate_apache,heart_rate_apache,878,0.957334,float64
hematocrit_apache,hematocrit_apache,19878,21.674136,float64
intubated_apache,intubated_apache,715,0.779606,float64
map_apache,map_apache,994,1.083816,float64
paco2_apache,paco2_apache,70868,77.271488,float64
paco2_for_ph_apache,paco2_for_ph_apache,70868,77.271488,float64
pao2_apache,pao2_apache,70868,77.271488,float64
ph_apache,ph_apache,70868,77.271488,float64
resprate_apache,resprate_apache,1234,1.345502,float64
sodium_apache,sodium_apache,18600,20.280658,float64
temp_apache,temp_apache,4108,4.479191,float64
urineoutput_apache,urineoutput_apache,48998,53.425360,float64
ventilated_apache,ventilated_apache,715,0.779606,float64
wbc_apache,wbc_apache,22012,24.000960,float64
d1_diasbp_invasive_max,d1_diasbp_invasive_max,67984,74.126896,float64
d1_diasbp_invasive_min,d1_diasbp_invasive_min,67984,74.126896,float64
d1_diasbp_max,d1_diasbp_max,165,0.179909,float64
d1_diasbp_min,d1_diasbp_min,165,0.179909,float64
d1_diasbp_noninvasive_max,d1_diasbp_noninvasive_max,1040,1.133972,float64
d1_diasbp_noninvasive_min,d1_diasbp_noninvasive_min,1040,1.133972,float64
d1_heartrate_max,d1_heartrate_max,145,0.158102,float64
d1_heartrate_min,d1_heartrate_min,145,0.158102,float64
d1_mbp_invasive_max,d1_mbp_invasive_max,67777,73.901192,float64
d1_mbp_invasive_min,d1_mbp_invasive_min,67777,73.901192,float64
d1_mbp_max,d1_mbp_max,220,0.239879,float64
d1_mbp_min,d1_mbp_min,220,0.239879,float64
d1_mbp_noninvasive_max,d1_mbp_noninvasive_max,1479,1.612639,float64
d1_mbp_noninvasive_min,d1_mbp_noninvasive_min,1479,1.612639,float64
d1_resprate_max,d1_resprate_max,385,0.419788,float64
d1_resprate_min,d1_resprate_min,385,0.419788,float64
d1_spo2_max,d1_spo2_max,333,0.363089,float64
d1_spo2_min,d1_spo2_min,333,0.363089,float64
d1_sysbp_invasive_max,d1_sysbp_invasive_max,67959,74.099637,float64
d1_sysbp_invasive_min,d1_sysbp_invasive_min,67959,74.099637,float64
d1_sysbp_max,d1_sysbp_max,159,0.173367,float64
d1_sysbp_min,d1_sysbp_min,159,0.173367,float64
d1_sysbp_noninvasive_max,d1_sysbp_noninvasive_max,1027,1.119798,float64
d1_sysbp_noninvasive_min,d1_sysbp_noninvasive_min,1027,1.119798,float64
d1_temp_max,d1_temp_max,2324,2.533992,float64
d1_temp_min,d1_temp_min,2324,2.533992,float64
h1_diasbp_invasive_max,h1_diasbp_invasive_max,74928,81.698342,float64
h1_diasbp_invasive_min,h1_diasbp_invasive_min,74928,81.698342,float64
h1_diasbp_max,h1_diasbp_max,3619,3.946005,float64
h1_diasbp_min,h1_diasbp_min,3619,3.946005,float64
h1_diasbp_noninvasive_max,h1_diasbp_noninvasive_max,7350,8.014131,float64
h1_diasbp_noninvasive_min,h1_diasbp_noninvasive_min,7350,8.014131,float64
h1_heartrate_max,h1_heartrate_max,2790,3.042099,float64
h1_heartrate_min,h1_heartrate_min,2790,3.042099,float64
h1_mbp_invasive_max,h1_mbp_invasive_max,74844,81.606751,float64
h1_mbp_invasive_min,h1_mbp_invasive_min,74844,81.606751,float64
h1_mbp_max,h1_mbp_max,4639,5.058171,float64
h1_mbp_min,h1_mbp_min,4639,5.058171,float64
h1_mbp_noninvasive_max,h1_mbp_noninvasive_max,9084,9.904812,float64
h1_mbp_noninvasive_min,h1_mbp_noninvasive_min,9084,9.904812,float64
h1_resprate_max,h1_resprate_max,4357,4.750690,float64
h1_resprate_min,h1_resprate_min,4357,4.750690,float64
h1_spo2_max,h1_spo2_max,4185,4.563148,float64
h1_spo2_min,h1_spo2_min,4185,4.563148,float64
h1_sysbp_invasive_max,h1_sysbp_invasive_max,74915,81.684167,float64
h1_sysbp_invasive_min,h1_sysbp_invasive_min,74915,81.684167,float64
h1_sysbp_max,h1_sysbp_max,3611,3.937283,float64
h1_sysbp_min,h1_sysbp_min,3611,3.937283,float64
h1_sysbp_noninvasive_max,h1_sysbp_noninvasive_max,7341,8.004318,float64
h1_sysbp_noninvasive_min,h1_sysbp_noninvasive_min,7341,8.004318,float64
h1_temp_max,h1_temp_max,21732,23.695659,float64
h1_temp_min,h1_temp_min,21732,23.695659,float64
d1_albumin_max,d1_albumin_max,49096,53.532215,float64
d1_albumin_min,d1_albumin_min,49096,53.532215,float64
d1_bilirubin_max,d1_bilirubin_max,53673,58.522783,float64
d1_bilirubin_min,d1_bilirubin_min,53673,58.522783,float64
d1_bun_max,d1_bun_max,10514,11.464024,float64
d1_bun_min,d1_bun_min,10514,11.464024,float64
d1_calcium_max,d1_calcium_max,13069,14.249888,float64
d1_calcium_min,d1_calcium_min,13069,14.249888,float64
d1_creatinine_max,d1_creatinine_max,10169,11.087850,float64
d1_creatinine_min,d1_creatinine_min,10169,11.087850,float64
d1_glucose_max,d1_glucose_max,5807,6.331709,float64
d1_glucose_min,d1_glucose_min,5807,6.331709,float64
d1_hco3_max,d1_hco3_max,15071,16.432785,float64
d1_hco3_min,d1_hco3_min,15071,16.432785,float64
d1_hemaglobin_max,d1_hemaglobin_max,12147,13.244578,float64
d1_hemaglobin_min,d1_hemaglobin_min,12147,13.244578,float64
d1_hematocrit_max,d1_hematocrit_max,11654,12.707032,float64
d1_hematocrit_min,d1_hematocrit_min,11654,12.707032,float64
d1_inr_max,d1_inr_max,57941,63.176431,float64
d1_inr_min,d1_inr_min,57941,63.176431,float64
d1_lactate_max,d1_lactate_max,68396,74.576123,float64
d1_lactate_min,d1_lactate_min,68396,74.576123,float64
d1_platelets_max,d1_platelets_max,13444,14.658772,float64
d1_platelets_min,d1_platelets_min,13444,14.658772,float64
d1_potassium_max,d1_potassium_max,9585,10.451081,float64
d1_potassium_min,d1_potassium_min,9585,10.451081,float64
d1_sodium_max,d1_sodium_max,10195,11.116199,float64
d1_sodium_min,d1_sodium_min,10195,11.116199,float64
d1_wbc_max,d1_wbc_max,13174,14.364376,float64
d1_wbc_min,d1_wbc_min,13174,14.364376,float64
h1_albumin_max,h1_albumin_max,83824,91.398166,float64
h1_albumin_min,h1_albumin_min,83824,91.398166,float64
h1_bilirubin_max,h1_bilirubin_max,84619,92.265001,float64
h1_bilirubin_min,h1_bilirubin_min,84619,92.265001,float64
h1_bun_max,h1_bun_max,75091,81.876070,float64
h1_bun_min,h1_bun_min,75091,81.876070,float64
h1_calcium_max,h1_calcium_max,75863,82.717826,float64
h1_calcium_min,h1_calcium_min,75863,82.717826,float64
h1_creatinine_max,h1_creatinine_max,74957,81.729962,float64
h1_creatinine_min,h1_creatinine_min,74957,81.729962,float64
h1_glucose_max,h1_glucose_max,52614,57.368094,float64
h1_glucose_min,h1_glucose_min,52614,57.368094,float64
h1_hco3_max,h1_hco3_max,76094,82.969699,float64
h1_hco3_min,h1_hco3_min,76094,82.969699,float64
h1_hemaglobin_max,h1_hemaglobin_max,73123,79.730245,float64
h1_hemaglobin_min,h1_hemaglobin_min,73123,79.730245,float64
h1_hematocrit_max,h1_hematocrit_max,73420,80.054082,float64
h1_hematocrit_min,h1_hematocrit_min,73420,80.054082,float64
h1_inr_max,h1_inr_max,57941,63.176431,float64
h1_inr_min,h1_inr_min,57941,63.176431,float64
h1_lactate_max,h1_lactate_max,84369,91.992411,float64
h1_lactate_min,h1_lactate_min,84369,91.992411,float64
h1_platelets_max,h1_platelets_max,75673,82.510658,float64
h1_platelets_min,h1_platelets_min,75673,82.510658,float64
h1_potassium_max,h1_potassium_max,72102,78.616990,float64
h1_potassium_min,h1_potassium_min,72102,78.616990,float64
h1_sodium_max,h1_sodium_max,72617,79.178524,float64
h1_sodium_min,h1_sodium_min,72617,79.178524,float64
h1_wbc_max,h1_wbc_max,75953,82.815958,float64
h1_wbc_min,h1_wbc_min,75953,82.815958,float64
d1_arterial_pco2_max,d1_arterial_pco2_max,59271,64.626607,float64
d1_arterial_pco2_min,d1_arterial_pco2_min,59271,64.626607,float64
d1_arterial_ph_max,d1_arterial_ph_max,60123,65.555592,float64
d1_arterial_ph_min,d1_arterial_ph_min,60123,65.555592,float64
d1_arterial_po2_max,d1_arterial_po2_max,59262,64.616794,float64
d1_arterial_po2_min,d1_arterial_po2_min,59262,64.616794,float64
d1_pao2fio2ratio_max,d1_pao2fio2ratio_max,66008,71.972349,float64
d1_pao2fio2ratio_min,d1_pao2fio2ratio_min,66008,71.972349,float64
h1_arterial_pco2_max,h1_arterial_pco2_max,75959,82.822501,float64
h1_arterial_pco2_min,h1_arterial_pco2_min,75959,82.822501,float64
h1_arterial_ph_max,h1_arterial_ph_max,76424,83.329517,float64
h1_arterial_ph_min,h1_arterial_ph_min,76424,83.329517,float64
h1_arterial_po2_max,h1_arterial_po2_max,75945,82.807236,float64
h1_arterial_po2_min,h1_arterial_po2_min,75945,82.807236,float64
h1_pao2fio2ratio_max,h1_pao2fio2ratio_max,80195,87.441257,float64
h1_pao2fio2ratio_min,h1_pao2fio2ratio_min,80195,87.441257,float64
apache_4a_hospital_death_prob,apache_4a_hospital_death_prob,7947,8.665075,float64
apache_4a_icu_death_prob,apache_4a_icu_death_prob,7947,8.665075,float64
aids,aids,715,0.779606,float64
cirrhosis,cirrhosis,715,0.779606,float64
diabetes_mellitus,diabetes_mellitus,715,0.779606,float64
hepatic_failure,hepatic_failure,715,0.779606,float64
immunosuppression,immunosuppression,715,0.779606,float64
leukemia,leukemia,715,0.779606,float64
lymphoma,lymphoma,715,0.779606,float64
solid_tumor_with_metastasis,solid_tumor_with_metastasis,715,0.779606,float64
apache_3j_bodysystem,apache_3j_bodysystem,1662,1.812175,object
apache_2_bodysystem,apache_2_bodysystem,1662,1.812175,object

In [ ]:
mis_val_table_ren_columns[mis_val_table_ren_columns.iloc[:,1] != 0].sort_values('% of Total Values', ascending=False)

,columns,Missing Values,% of Total Values,Data_Types
h1_bilirubin_max,h1_bilirubin_max,84619,92.265001,float64
h1_bilirubin_min,h1_bilirubin_min,84619,92.265001,float64
h1_lactate_min,h1_lactate_min,84369,91.992411,float64
h1_lactate_max,h1_lactate_max,84369,91.992411,float64
h1_albumin_max,h1_albumin_max,83824,91.398166,float64
h1_albumin_min,h1_albumin_min,83824,91.398166,float64
h1_pao2fio2ratio_min,h1_pao2fio2ratio_min,80195,87.441257,float64
h1_pao2fio2ratio_max,h1_pao2fio2ratio_max,80195,87.441257,float64
h1_arterial_ph_min,h1_arterial_ph_min,76424,83.329517,float64
h1_arterial_ph_max,h1_arterial_ph_max,76424,83.329517,float64
h1_hco3_min,h1_hco3_min,76094,82.969699,float64
h1_hco3_max,h1_hco3_max,76094,82.969699,float64
h1_arterial_pco2_min,h1_arterial_pco2_min,75959,82.822501,float64
h1_arterial_pco2_max,h1_arterial_pco2_max,75959,82.822501,float64
h1_wbc_max,h1_wbc_max,75953,82.815958,float64
h1_wbc_min,h1_wbc_min,75953,82.815958,float64
h1_arterial_po2_max,h1_arterial_po2_max,75945,82.807236,float64
h1_arterial_po2_min,h1_arterial_po2_min,75945,82.807236,float64
h1_calcium_min,h1_calcium_min,75863,82.717826,float64
h1_calcium_max,h1_calcium_max,75863,82.717826,float64
h1_platelets_max,h1_platelets_max,75673,82.510658,float64
h1_platelets_min,h1_platelets_min,75673,82.510658,float64
h1_bun_min,h1_bun_min,75091,81.876070,float64
h1_bun_max,h1_bun_max,75091,81.876070,float64
h1_creatinine_min,h1_creatinine_min,74957,81.729962,float64
h1_creatinine_max,h1_creatinine_max,74957,81.729962,float64
h1_diasbp_invasive_max,h1_diasbp_invasive_max,74928,81.698342,float64
h1_diasbp_invasive_min,h1_diasbp_invasive_min,74928,81.698342,float64
h1_sysbp_invasive_max,h1_sysbp_invasive_max,74915,81.684167,float64
h1_sysbp_invasive_min,h1_sysbp_invasive_min,74915,81.684167,float64
h1_mbp_invasive_min,h1_mbp_invasive_min,74844,81.606751,float64
h1_mbp_invasive_max,h1_mbp_invasive_max,74844,81.606751,float64
h1_hematocrit_min,h1_hematocrit_min,73420,80.054082,float64
h1_hematocrit_max,h1_hematocrit_max,73420,80.054082,float64
h1_hemaglobin_max,h1_hemaglobin_max,73123,79.730245,float64
h1_hemaglobin_min,h1_hemaglobin_min,73123,79.730245,float64
h1_sodium_max,h1_sodium_max,72617,79.178524,float64
h1_sodium_min,h1_sodium_min,72617,79.178524,float64
h1_potassium_min,h1_potassium_min,72102,78.616990,float64
h1_potassium_max,h1_potassium_max,72102,78.616990,float64
ph_apache,ph_apache,70868,77.271488,float64
pao2_apache,pao2_apache,70868,77.271488,float64
paco2_for_ph_apache,paco2_for_ph_apache,70868,77.271488,float64
paco2_apache,paco2_apache,70868,77.271488,float64
fio2_apache,fio2_apache,70868,77.271488,float64
d1_lactate_max,d1_lactate_max,68396,74.576123,float64
d1_lactate_min,d1_lactate_min,68396,74.576123,float64
d1_diasbp_invasive_min,d1_diasbp_invasive_min,67984,74.126896,float64
d1_diasbp_invasive_max,d1_diasbp_invasive_max,67984,74.126896,float64
d1_sysbp_invasive_max,d1_sysbp_invasive_max,67959,74.099637,float64
d1_sysbp_invasive_min,d1_sysbp_invasive_min,67959,74.099637,float64
d1_mbp_invasive_min,d1_mbp_invasive_min,67777,73.901192,float64
d1_mbp_invasive_max,d1_mbp_invasive_max,67777,73.901192,float64
d1_pao2fio2ratio_min,d1_pao2fio2ratio_min,66008,71.972349,float64
d1_pao2fio2ratio_max,d1_pao2fio2ratio_max,66008,71.972349,float64
d1_arterial_ph_min,d1_arterial_ph_min,60123,65.555592,float64
d1_arterial_ph_max,d1_arterial_ph_max,60123,65.555592,float64
d1_arterial_pco2_max,d1_arterial_pco2_max,59271,64.626607,float64
d1_arterial_pco2_min,d1_arterial_pco2_min,59271,64.626607,float64
d1_arterial_po2_min,d1_arterial_po2_min,59262,64.616794,float64
d1_arterial_po2_max,d1_arterial_po2_max,59262,64.616794,float64
bilirubin_apache,bilirubin_apache,58134,63.386870,float64
h1_inr_max,h1_inr_max,57941,63.176431,float64
d1_inr_min,d1_inr_min,57941,63.176431,float64
h1_inr_min,h1_inr_min,57941,63.176431,float64
d1_inr_max,d1_inr_max,57941,63.176431,float64
albumin_apache,albumin_apache,54379,59.292576,float64
d1_bilirubin_min,d1_bilirubin_min,53673,58.522783,float64
d1_bilirubin_max,d1_bilirubin_max,53673,58.522783,float64
h1_glucose_min,h1_glucose_min,52614,57.368094,float64
h1_glucose_max,h1_glucose_max,52614,57.368094,float64
d1_albumin_min,d1_albumin_min,49096,53.532215,float64
d1_albumin_max,d1_albumin_max,49096,53.532215,float64
urineoutput_apache,urineoutput_apache,48998,53.425360,float64
wbc_apache,wbc_apache,22012,24.000960,float64
h1_temp_min,h1_temp_min,21732,23.695659,float64
h1_temp_max,h1_temp_max,21732,23.695659,float64
hospital_admit_source,hospital_admit_source,21409,23.343474,object
hematocrit_apache,hematocrit_apache,19878,21.674136,float64
bun_apache,bun_apache,19262,21.002475,float64
creatinine_apache,creatinine_apache,18853,20.556519,float64
sodium_apache,sodium_apache,18600,20.280658,float64
d1_hco3_max,d1_hco3_max,15071,16.432785,float64
d1_hco3_min,d1_hco3_min,15071,16.432785,float64
d1_platelets_max,d1_platelets_max,13444,14.658772,float64
d1_platelets_min,d1_platelets_min,13444,14.658772,float64
d1_wbc_max,d1_wbc_max,13174,14.364376,float64
d1_wbc_min,d1_wbc_min,13174,14.364376,float64
d1_calcium_max,d1_calcium_max,13069,14.249888,float64
d1_calcium_min,d1_calcium_min,13069,14.249888,float64
d1_hemaglobin_min,d1_hemaglobin_min,12147,13.244578,float64
d1_hemaglobin_max,d1_hemaglobin_max,12147,13.244578,float64
d1_hematocrit_min,d1_hematocrit_min,11654,12.707032,float64
d1_hematocrit_max,d1_hematocrit_max,11654,12.707032,float64
glucose_apache,glucose_apache,11036,12.033190,float64
d1_bun_max,d1_bun_max,10514,11.464024,float64
d1_bun_min,d1_bun_min,10514,11.464024,float64
d1_sodium_max,d1_sodium_max,10195,11.116199,float64
d1_sodium_min,d1_sodium_min,10195,11.116199,float64
d1_creatinine_max,d1_creatinine_max,10169,11.087850,float64
d1_creatinine_min,d1_creatinine_min,10169,11.087850,float64
d1_potassium_min,d1_potassium_min,9585,10.451081,float64
d1_potassium_max,d1_potassium_max,9585,10.451081,float64
h1_mbp_noninvasive_max,h1_mbp_noninvasive_max,9084,9.904812,float64
h1_mbp_noninvasive_min,h1_mbp_noninvasive_min,9084,9.904812,float64
apache_4a_hospital_death_prob,apache_4a_hospital_death_prob,7947,8.665075,float64
apache_4a_icu_death_prob,apache_4a_icu_death_prob,7947,8.665075,float64
h1_diasbp_noninvasive_max,h1_diasbp_noninvasive_max,7350,8.014131,float64
h1_diasbp_noninvasive_min,h1_diasbp_noninvasive_min,7350,8.014131,float64
h1_sysbp_noninvasive_max,h1_sysbp_noninvasive_max,7341,8.004318,float64
h1_sysbp_noninvasive_min,h1_sysbp_noninvasive_min,7341,8.004318,float64
d1_glucose_max,d1_glucose_max,5807,6.331709,float64
d1_glucose_min,d1_glucose_min,5807,6.331709,float64
h1_mbp_max,h1_mbp_max,4639,5.058171,float64
h1_mbp_min,h1_mbp_min,4639,5.058171,float64
h1_resprate_min,h1_resprate_min,4357,4.750690,float64
h1_resprate_max,h1_resprate_max,4357,4.750690,float64
age,age,4228,4.610033,float64
h1_spo2_min,h1_spo2_min,4185,4.563148,float64
h1_spo2_max,h1_spo2_max,4185,4.563148,float64
temp_apache,temp_apache,4108,4.479191,float64
h1_diasbp_min,h1_diasbp_min,3619,3.946005,float64
h1_diasbp_max,h1_diasbp_max,3619,3.946005,float64
h1_sysbp_max,h1_sysbp_max,3611,3.937283,float64
h1_sysbp_min,h1_sysbp_min,3611,3.937283,float64
bmi,bmi,3429,3.738837,float64
h1_heartrate_max,h1_heartrate_max,2790,3.042099,float64
h1_heartrate_min,h1_heartrate_min,2790,3.042099,float64
weight,weight,2720,2.965774,float64
d1_temp_max,d1_temp_max,2324,2.533992,float64
d1_temp_min,d1_temp_min,2324,2.533992,float64
gcs_eyes_apache,gcs_eyes_apache,1901,2.072770,float64
gcs_motor_apache,gcs_motor_apache,1901,2.072770,float64
gcs_verbal_apache,gcs_verbal_apache,1901,2.072770,float64
apache_3j_bodysystem,apache_3j_bodysystem,1662,1.812175,object
apache_2_diagnosis,apache_2_diagnosis,1662,1.812175,float64
apache_2_bodysystem,apache_2_bodysystem,1662,1.812175,object
d1_mbp_noninvasive_min,d1_mbp_noninvasive_min,1479,1.612639,float64
d1_mbp_noninvasive_max,d1_mbp_noninvasive_max,1479,1.612639,float64
ethnicity,ethnicity,1395,1.521049,object
height,height,1334,1.454538,float64
resprate_apache,resprate_apache,1234,1.345502,float64
apache_3j_diagnosis,apache_3j_diagnosis,1101,1.200484,float64
d1_diasbp_noninvasive_min,d1_diasbp_noninvasive_min,1040,1.133972,float64
d1_diasbp_noninvasive_max,d1_diasbp_noninvasive_max,1040,1.133972,float64
gcs_unable_apache,gcs_unable_apache,1037,1.130701,float64
d1_sysbp_noninvasive_min,d1_sysbp_noninvasive_min,1027,1.119798,float64
d1_sysbp_noninvasive_max,d1_sysbp_noninvasive_max,1027,1.119798,float64
map_apache,map_apache,994,1.083816,float64
heart_rate_apache,heart_rate_apache,878,0.957334,float64
lymphoma,lymphoma,715,0.779606,float64
intubated_apache,intubated_apache,715,0.779606,float64
aids,aids,715,0.779606,float64
hepatic_failure,hepatic_failure,715,0.779606,float64
immunosuppression,immunosuppression,715,0.779606,float64
solid_tumor_with_metastasis,solid_tumor_with_metastasis,715,0.779606,float64
leukemia,leukemia,715,0.779606,float64
cirrhosis,cirrhosis,715,0.779606,float64
arf_apache,arf_apache,715,0.779606,float64
ventilated_apache,ventilated_apache,715,0.779606,float64
diabetes_mellitus,diabetes_mellitus,715,0.779606,float64
d1_resprate_max,d1_resprate_max,385,0.419788,float64
d1_resprate_min,d1_resprate_min,385,0.419788,float64
d1_spo2_min,d1_spo2_min,333,0.363089,float64
d1_spo2_max,d1_spo2_max,333,0.363089,float64
d1_mbp_max,d1_mbp_max,220,0.239879,float64
d1_mbp_min,d1_mbp_min,220,0.239879,float64
d1_diasbp_max,d1_diasbp_max,165,0.179909,float64
d1_diasbp_min,d1_diasbp_min,165,0.179909,float64
d1_sysbp_min,d1_sysbp_min,159,0.173367,float64
d1_sysbp_max,d1_sysbp_max,159,0.173367,float64
d1_heartrate_max,d1_heartrate_max,145,0.158102,float64
d1_heartrate_min,d1_heartrate_min,145,0.158102,float64
icu_admit_source,icu_admit_source,112,0.122120,object
gender,gender,25,0.027259,object

In [ ]:
 mis_val_table_ren_columns =mis_val_table_ren_columns[mis_val_table_ren_columns.iloc[:,1] != 0].sort_values('% of Total Values', ascending=False).round(1)

In [ ]:
mis_val_table_ren_columns.info()

<class 'pandas.core.frame.DataFrame'>
Index: 175 entries, h1_bilirubin_max to gender
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   columns            175 non-null    object
 1   Missing Values     175 non-null    int64
 2   % of Total Values  175 non-null    float64
 3   Data_Types         175 non-null    object
dtypes: float64(1), int64(1), object(2)
memory usage: 6.8+ KB

In [ ]:
mis_val_table_ren_columns.head()

,columns,Missing Values,% of Total Values,Data_Types
h1_bilirubin_max,h1_bilirubin_max,84619,92.3,float64
h1_bilirubin_min,h1_bilirubin_min,84619,92.3,float64
h1_lactate_min,h1_lactate_min,84369,92.0,float64
h1_lactate_max,h1_lactate_max,84369,92.0,float64
h1_albumin_max,h1_albumin_max,83824,91.4,float64

In [ ]:
mis_val_table_ren_columns.columns

Index(['columns', 'Missing Values', '% of Total Values', 'Data_Types'], dtype='object')

In [ ]:
mis_val_table_ren_columns.shape

(175, 4)

In [ ]:
mis_val_table_ren_columns.head(2)

,columns,Missing Values,% of Total Values,Data_Types
h1_bilirubin_max,h1_bilirubin_max,84619,92.3,float64
h1_bilirubin_min,h1_bilirubin_min,84619,92.3,float64

In [ ]:
mis_val_table_ren_columns.shape

(175, 4)

In [ ]:
print ("Your selected dataframe has " + str(df.shape[1]) + " columns.\n""There are " + str(mis_val_table_ren_columns.shape[0]) +" columns that have missing values.")

Your selected dataframe has 183 columns.
There are 175 columns that have missing values.

In [ ]:
mis_val_table_ren_columns.head()

,columns,Missing Values,% of Total Values,Data_Types
h1_bilirubin_max,h1_bilirubin_max,84619,92.3,float64
h1_bilirubin_min,h1_bilirubin_min,84619,92.3,float64
h1_lactate_min,h1_lactate_min,84369,92.0,float64
h1_lactate_max,h1_lactate_max,84369,92.0,float64
h1_albumin_max,h1_albumin_max,83824,91.4,float64

In [ ]:
mis_val_table_ren_columns['Missing Values']=mis_val_table_ren_columns['Missing Values'].astype(int)
mis_val_table_ren_columns['% of Total Values']=mis_val_table_ren_columns['% of Total Values'].astype(int)

In [ ]:
mis_val_table_ren_columns.info()

<class 'pandas.core.frame.DataFrame'>
Index: 175 entries, h1_bilirubin_max to gender
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   columns            175 non-null    object
 1   Missing Values     175 non-null    int64
 2   % of Total Values  175 non-null    int64
 3   Data_Types         175 non-null    object
dtypes: int64(2), object(2)
memory usage: 6.8+ KB

##Now we have list of columns which have descending order missing values % so start dropping those

In [ ]:
#df_filtered = df[df['Age'] >= 25]
#print(df_filtered.head(15)
# Print the shape of the dataframe
#print(df_filtered.shape)

mis_val_table_ren_columns.drop(mis_val_table_ren_columns[mis_val_table_ren_columns['% of Total Values'] > 80].index, inplace = True)#

In [ ]:
mis_val_table_ren_columns.shape

(143, 4)

In [ ]:
mis_val_table_ren_columns.head(10)

,columns,Missing Values,% of Total Values,Data_Types
h1_hematocrit_min,h1_hematocrit_min,73420,80,float64
h1_hematocrit_max,h1_hematocrit_max,73420,80,float64
h1_hemaglobin_max,h1_hemaglobin_max,73123,79,float64
h1_hemaglobin_min,h1_hemaglobin_min,73123,79,float64
h1_sodium_max,h1_sodium_max,72617,79,float64
h1_sodium_min,h1_sodium_min,72617,79,float64
h1_potassium_min,h1_potassium_min,72102,78,float64
h1_potassium_max,h1_potassium_max,72102,78,float64
ph_apache,ph_apache,70868,77,float64
pao2_apache,pao2_apache,70868,77,float64

In [ ]:
#reset the index
mis_val_table_ren_columns=mis_val_table_ren_columns.reset_index(drop=True)

In [ ]:
mis_val_table_ren_columns.head()

             columns  Missing Values  % of Total Values Data_Types
0  h1_hematocrit_min           73420                 80    float64
1  h1_hematocrit_max           73420                 80    float64
2  h1_hemaglobin_max           73123                 79    float64
3  h1_hemaglobin_min           73123                 79    float64
4      h1_sodium_max           72617                 79    float64

In [ ]:
mis_val_table_ren_columns['columns'].values

array(['h1_hematocrit_min', 'h1_hematocrit_max', 'h1_hemaglobin_max',
       'h1_hemaglobin_min', 'h1_sodium_max', 'h1_sodium_min',
       'h1_potassium_min', 'h1_potassium_max', 'ph_apache', 'pao2_apache',
       'paco2_for_ph_apache', 'paco2_apache', 'fio2_apache',
       'd1_lactate_max', 'd1_lactate_min', 'd1_diasbp_invasive_min',
       'd1_diasbp_invasive_max', 'd1_sysbp_invasive_max',
       'd1_sysbp_invasive_min', 'd1_mbp_invasive_min',
       'd1_mbp_invasive_max', 'd1_pao2fio2ratio_min',
       'd1_pao2fio2ratio_max', 'd1_arterial_ph_min', 'd1_arterial_ph_max',
       'd1_arterial_pco2_max', 'd1_arterial_pco2_min',
       'd1_arterial_po2_min', 'd1_arterial_po2_max', 'bilirubin_apache',
       'h1_inr_max', 'd1_inr_min', 'h1_inr_min', 'd1_inr_max',
       'albumin_apache', 'd1_bilirubin_min', 'd1_bilirubin_max',
       'h1_glucose_min', 'h1_glucose_max', 'd1_albumin_min',
       'd1_albumin_max', 'urineoutput_apache', 'wbc_apache',
       'h1_temp_min', 'h1_temp_max', 'hospital_admit_source',
       'hematocrit_apache', 'bun_apache', 'creatinine_apache',
       'sodium_apache', 'd1_hco3_max', 'd1_hco3_min', 'd1_platelets_max',
       'd1_platelets_min', 'd1_wbc_max', 'd1_wbc_min', 'd1_calcium_max',
       'd1_calcium_min', 'd1_hemaglobin_min', 'd1_hemaglobin_max',
       'd1_hematocrit_min', 'd1_hematocrit_max', 'glucose_apache',
       'd1_bun_max', 'd1_bun_min', 'd1_sodium_max', 'd1_sodium_min',
       'd1_creatinine_max', 'd1_creatinine_min', 'd1_potassium_min',
       'd1_potassium_max', 'h1_mbp_noninvasive_max',
       'h1_mbp_noninvasive_min', 'apache_4a_hospital_death_prob',
       'apache_4a_icu_death_prob', 'h1_diasbp_noninvasive_max',
       'h1_diasbp_noninvasive_min', 'h1_sysbp_noninvasive_max',
       'h1_sysbp_noninvasive_min', 'd1_glucose_max', 'd1_glucose_min',
       'h1_mbp_max', 'h1_mbp_min', 'h1_resprate_min', 'h1_resprate_max',
       'age', 'h1_spo2_min', 'h1_spo2_max', 'temp_apache',
       'h1_diasbp_min', 'h1_diasbp_max', 'h1_sysbp_max', 'h1_sysbp_min',
       'bmi', 'h1_heartrate_max', 'h1_heartrate_min', 'weight',
       'd1_temp_max', 'd1_temp_min', 'gcs_eyes_apache',
       'gcs_motor_apache', 'gcs_verbal_apache', 'apache_3j_bodysystem',
       'apache_2_diagnosis', 'apache_2_bodysystem',
       'd1_mbp_noninvasive_min', 'd1_mbp_noninvasive_max', 'ethnicity',
       'height', 'resprate_apache', 'apache_3j_diagnosis',
       'd1_diasbp_noninvasive_min', 'd1_diasbp_noninvasive_max',
       'gcs_unable_apache', 'd1_sysbp_noninvasive_min',
       'd1_sysbp_noninvasive_max', 'map_apache', 'heart_rate_apache',
       'lymphoma', 'intubated_apache', 'aids', 'hepatic_failure',
       'immunosuppression', 'solid_tumor_with_metastasis', 'leukemia',
       'cirrhosis', 'arf_apache', 'ventilated_apache',
       'diabetes_mellitus', 'd1_resprate_max', 'd1_resprate_min',
       'd1_spo2_min', 'd1_spo2_max', 'd1_mbp_max', 'd1_mbp_min',
       'd1_diasbp_max', 'd1_diasbp_min', 'd1_sysbp_min', 'd1_sysbp_max',
       'd1_heartrate_max', 'd1_heartrate_min', 'icu_admit_source',
       'gender'], dtype=object)

In [ ]:
## considering the "mis_val_table_ren_columns" dataframe's first column that is COLUMNS 
#because after deleting all the values which are having more than 80% missing values now we should only consider 
# the columns that is dataframes columns list in the list values so we can take these columns list in df3 dataframe
column_list_with_removed_val=mis_val_table_ren_columns['columns'].values

In [ ]:
type(column_list_with_removed_val)

numpy.ndarray

In [ ]:
df3[column_list_with_removed_val].head()

,h1_hematocrit_min,h1_hematocrit_max,h1_hemaglobin_max,h1_hemaglobin_min,h1_sodium_max,h1_sodium_min,h1_potassium_min,h1_potassium_max,ph_apache,pao2_apache,paco2_for_ph_apache,paco2_apache,fio2_apache,d1_lactate_max,d1_lactate_min,d1_diasbp_invasive_min,d1_diasbp_invasive_max,d1_sysbp_invasive_max,d1_sysbp_invasive_min,d1_mbp_invasive_min,d1_mbp_invasive_max,d1_pao2fio2ratio_min,d1_pao2fio2ratio_max,d1_arterial_ph_min,d1_arterial_ph_max,d1_arterial_pco2_max,d1_arterial_pco2_min,d1_arterial_po2_min,d1_arterial_po2_max,bilirubin_apache,h1_inr_max,d1_inr_min,h1_inr_min,d1_inr_max,albumin_apache,d1_bilirubin_min,d1_bilirubin_max,h1_glucose_min,h1_glucose_max,d1_albumin_min,d1_albumin_max,urineoutput_apache,wbc_apache,h1_temp_min,h1_temp_max,hospital_admit_source,hematocrit_apache,bun_apache,creatinine_apache,sodium_apache,d1_hco3_max,d1_hco3_min,d1_platelets_max,d1_platelets_min,d1_wbc_max,d1_wbc_min,d1_calcium_max,d1_calcium_min,d1_hemaglobin_min,d1_hemaglobin_max,d1_hematocrit_min,d1_hematocrit_max,glucose_apache,d1_bun_max,d1_bun_min,d1_sodium_max,d1_sodium_min,d1_creatinine_max,d1_creatinine_min,d1_potassium_min,d1_potassium_max,h1_mbp_noninvasive_max,h1_mbp_noninvasive_min,apache_4a_hospital_death_prob,apache_4a_icu_death_prob,h1_diasbp_noninvasive_max,h1_diasbp_noninvasive_min,h1_sysbp_noninvasive_max,h1_sysbp_noninvasive_min,d1_glucose_max,d1_glucose_min,h1_mbp_max,h1_mbp_min,h1_resprate_min,h1_resprate_max,age,h1_spo2_min,h1_spo2_max,temp_apache,h1_diasbp_min,h1_diasbp_max,h1_sysbp_max,h1_sysbp_min,bmi,h1_heartrate_max,h1_heartrate_min,weight,d1_temp_max,d1_temp_min,gcs_eyes_apache,gcs_motor_apache,gcs_verbal_apache,apache_3j_bodysystem,apache_2_diagnosis,apache_2_bodysystem,d1_mbp_noninvasive_min,d1_mbp_noninvasive_max,ethnicity,height,resprate_apache,apache_3j_diagnosis,d1_diasbp_noninvasive_min,d1_diasbp_noninvasive_max,gcs_unable_apache,d1_sysbp_noninvasive_min,d1_sysbp_noninvasive_max,map_apache,heart_rate_apache,lymphoma,intubated_apache,aids,hepatic_failure,immunosuppression,solid_tumor_with_metastasis,leukemia,cirrhosis,arf_apache,ventilated_apache,diabetes_mellitus,d1_resprate_max,d1_resprate_min,d1_spo2_min,d1_spo2_max,d1_mbp_max,d1_mbp_min,d1_diasbp_max,d1_diasbp_min,d1_sysbp_min,d1_sysbp_max,d1_heartrate_max,d1_heartrate_min,icu_admit_source,gender
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.3,1.0,32.0,46.0,122.0,64.0,40.0,66.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.4,NaN,NaN,NaN,NaN,2.3,0.4,0.4,NaN,NaN,2.3,2.3,NaN,14.1,37.5,39.5,Floor,27.4,31.0,2.51,134.0,19.0,15.0,233.0,233.0,14.1,14.1,8.5,7.4,8.9,8.9,27.4,27.4,168.0,31.0,30.0,136.0,134.0,2.51,2.23,3.4,4.0,86.0,85.0,0.10,0.05,68.0,63.0,131.0,115.0,168.0,109.0,86.0,85.0,18.0,26.0,68.0,74.0,100.0,39.3,63.0,68.0,131.0,115.0,22.73,119.0,108.0,73.9,39.9,37.2,3.0,6.0,4.0,Sepsis,113.0,Cardiovascular,46.0,89.0,Caucasian,180.3,36.0,502.01,37.0,68.0,0.0,73.0,131.0,40.0,118.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,34.0,10.0,74.0,100.0,89.0,46.0,68.0,37.0,73.0,131.0,119.0,72.0,Floor,M
1,36.9,36.9,11.3,11.3,145.0,145.0,4.2,4.2,7.45,51.0,37.0,37.0,1.0,3.5,3.5,NaN,NaN,NaN,NaN,NaN,NaN,51.000000,54.8,7.45,7.45,37.0,37.0,51.0,51.0,NaN,1.3,1.3,1.3,1.3,NaN,0.5,0.5,143.0,145.0,1.6,1.6,NaN,12.7,36.3,36.3,Floor,36.9,9.0,0.56,145.0,27.0,26.0,557.0,487.0,23.3,12.7,8.6,8.0,11.1,11.3,36.1,36.9,145.0,11.0,9.0,145.0,145.0,0.71,0.56,3.8,4.2,85.0,57.0,0.47,0.29,61.0,48.0,95.0,71.0,145.0,128.0,85.0,57.0,28.0,31.0,77.0,70.0,95.0,35.1,48.0,61.0,95.0,71.0,27.42,114.0,100.0,70.2,36.3,35.1,1.0,3.0,1.0,Respiratory,108.0,Respiratory,38.0,120.0,Caucasian,160.0,33.0,203.01,31.0,95.0,0.0,67.0,159.0,46.0,120.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,32.0,12.0,70.0,100.0,120.0,38.0,95.0,31.0,67.0,159.0,118.0,72.0,Floor,F
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36.7,36.7,Emergency Department,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,91.0,83.0,0.00,0.00,88.0,58.0,148.0,124.0,NaN,NaN,91.0,83.0,16.0,20.0,25.0,91.0,98.0,36.7,58.0,88.0,148.0,124.0,31.95,96.0,78.0,95.3,37.0,36.7,3.0,6.0,5.0,Metabolic,122.0,Metabolic,68.0,102.0,Caucasian,172.7,37.0,703.03,48.0,88.0,0.0,105.0,148.0,68.0,102.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,21.0,8.0,91.0,98.0,102.0,68.0,88.0,48.0,105.0,148.0,96.0,68.0,Accident & Emergency,F
3,34.0,34.0,11.6,11.6,NaN,NaN,NaN,NaN,7.39,142.0,30.0,30.0,0.6,NaN,NaN,30.0,62.0,164.0,78.0,52.0,92.0,236.666667,342.5,7.34,7.44,37.0,27.0,102.0,337.0,NaN,1.6,1.1,1.1,1.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,34.8,35.6,Operating Room,25.9,NaN,NaN,NaN,NaN,NaN,198.0,43.0,9.0,8.0,NaN,NaN,8.9,11.6,25.9,34.0,185.0,NaN,NaN,NaN,NaN,NaN,NaN,3.5,5.0,NaN,NaN,0.04,0.03,NaN,NaN,NaN,NaN,185.0,88.0,92.0,71.0,11.0,12.0,81.0,99.0,100.0,34.8,44.0,62.0,136.0,106.0,22.64,100.0,96.0,61.7,38.0,34.8,4.0,6.0,5.0,Cardiovascular,203.0,Cardiovascular,84.0,84.0,Caucasian,165.1,4.0,1206.03,42.0,48.0,0.0,84.0,158.0,60.0,114.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,23.0,7.0,95.0,100.0,84.0,84.0,48.0,42.0,84.0,158.0,116.0,92.0,Operating Room / Recovery,F
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,104.0,92.0,NaN,NaN,99.0,68.0,130.0,120.0,NaN,NaN,104.0,92.0,NaN,NaN,19.0,100.0,100.0,36.7,68.0,99.0,130.0,120.0,NaN,89.0,76.0,NaN,37.2,36.7,NaN,NaN,NaN,Trauma,119.0,Trauma,90.0,104.0,Caucasian,188.0,16.0,601.01,57.0,99.0,NaN,120.0,147.0,103.0,60.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,18.0,16.0,96.0,100.0,104.0,90.0,99.0,57.0,120.0,147.0,89.0,60.0,Accident & Emergency,M

In [ ]:
df3[column_list_with_removed_val].shape

(91713, 143)

ValueError                                Traceback (most recent call last)
<ipython-input-21-a97566e4d887> in <module>()
----> 1 for Miss_values, Total_values, Data_types in mis_val_table_ren_columns.iterrows():
      2   print(Miss_values, Total_values, Data_types)
      3   print()

ValueError: not enough values to unpack (expected 3, got 2)

Ans: 1. First should understand the error meaning

Error not enough values to unpack (expected 3, got 2) means:

a 2 part tuple, but assign to 3 values